# Change these first
owner: Andrew-Forster
repo: uptime # The name of this repository

assignees:
  - Andrew-Forster

sites:
  - name: Personal / About Site
    url: https://andrewjf.com
  - name: Blog Site
    url: https://blog.andrewjf.com
  - name: Alchemy Analytix
    url: https://alchemyanalytix.com/

status-website:
  theme: dark
  cname: status.andrewjf.com
  logoUrl: https://andrewjf.com/Assets/Images/Me.jpg
  name: Uptime
  introTitle: "This site is used to track up-time and down-time for website created by Andrew."
  introMessage: The status of my sites are listed below
  navbar:
    - title: Uptime Repo
      href: https://github.com/$OWNER/$REPO
    - title: Personal / About Site
      url: https://andrewjf.com
    - title: Blog Site
      url: https://blog.andrewjf.com
    - title: Alchemy Analytix
      url: https://alchemyanalytix.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
