# Change these first
owner: andrew-forster
repo: uptime # The name of this repository

sites:
  - name: Personal / About Site
    url: https://andrewjf.com
  - name: Blog Site
    url: https://blog.andrewjf.com
  - name: Alchemy Analytix
    url: https://alchemyanalytix.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://andrewjf.com/Assets/Images/Me.jpg
  name: Andrews Uptime Tracker
  introTitle: "This site is used to track up-time and down-time for website created by Andrew."
  introMessage: The status of my sites are listed below
  navbar:
    - title: Status
      href: /uptime
    - title: Uptime Repo
      href: https://github.com/$OWNER/$REPO
    - title: Personal / About Site
      url: https://andrewjf.com
    - title: Blog Site
      url: https://blog.andrewjf.com
    - title: Alchemy Analytix
      url: https://alchemyanalytix.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
